
* Maria Madalena

- O que sabemos sobre essa mulher?

- Bible verses   

+ Matthew 27:56: entre as quais se achavam Maria Madalena, Maria, mãe de Tiago e de José, e a mãe dos filhos de Zebedeu. (PorRecebida)

+ Matthew 28:1: No fim do sábado, quando já despontava o primeiro dia da semana, Maria Madalena e a outra Maria foram ver o sepulcro. (PorRecebida)

+ Mark 15:47: E Maria Madalena e Maria, mãe de José, observavam onde fora posto. (PorRecebida)

+ Mark 16:9: Ora, havendo Jesus ressuscitado cedo no primeiro dia da semana, apareceu primeiramente a Maria Madalena, da qual tinha expulsado sete demônios. (PorRecebida)

+ Luke 8:2: bem como algumas mulheres que haviam sido curadas de espíritos malignos e de enfermidades: Maria, chamada Madalena, da qual tinham saído sete demônios. (PorRecebida)

+ John 20:18: E foi Maria Madalena anunciar aos discípulos que tinha visto o Senhor e que ele lhe dissera estas coisas. (PorRecebida)

- Life Summarized Recipient of a great salvation

+ Luke 8:2: bem como algumas mulheres que haviam sido curadas de espíritos malignos e de enfermidades: Maria, chamada Madalena, da qual tinham saído sete demônios. (PorRecebida)

- Showed her gratitude By ministering to Christ

+ Mark 15:40: Também ali estavam algumas mulheres olhando de longe, entre elas Maria Madalena, Maria, mãe de Tiago o Menor e de José, e Salomé;

+ Mark 15:41: as quais o seguiam e o serviam quando ele estava na Galileia; e muitas outras que tinham subido com ele a Jerusalém. (PorRecebida)

- By her presence at the cross

+ John 19:25: Estavam em pé, junto à cruz de Jesus, sua mãe, e a irmã de sua mãe, e Maria, mulher de Clopas, e Maria Madalena. (PorRecebida)

- By her presence at the sepulchre

+ Matthew 27:61: Mas achavam-se ali Maria Madalena e a outra Maria, sentadas defronte do sepulcro. (PorRecebida)

+ Matthew 28:1: No fim do sábado, quando já despontava o primeiro dia da semana, Maria Madalena e a outra Maria foram ver o sepulcro. (PorRecebida)

- Was the first person to whom Christ appeared after his resurrection

+ Mark 16:9: Ora, havendo Jesus ressuscitado cedo no primeiro dia da semana, apareceu primeiramente a Maria Madalena, da qual tinha expulsado sete demônios. (PorRecebida)

- Given a wonderful revelation

+ John 20:11: Maria, porém, estava em pé, diante do sepulcro, a chorar. Enquanto chorava, abaixou-se a olhar para dentro do sepulcro,
+ John 20:12: e viu dois anjos vestidos de branco sentados onde jazera o corpo de Jesus, um à cabeceira e outro aos pés.
+ John 20:13: E perguntaram-lhe eles: Mulher, por que choras? Respondeu-lhes: Porque tiraram o meu Senhor, e não sei onde o puseram.
+ John 20:14: Ao dizer isso, voltou-se para trás, e viu a Jesus ali em pé, mas não sabia que era Jesus.
+ John 20:15: Perguntou-lhe Jesus: Mulher, por que choras? A quem procuras? Ela, julgando que fosse o jardineiro, respondeu-lhe: Senhor, se tu o levaste, dize-me onde o puseste, e eu o levarei.
+ John 20:16: Disse-lhe Jesus: Maria! Ela, virando-se, disse-lhe em hebraico: Raboni, que quer dizer, Mestre.
+ John 20:17: Disse-lhe Jesus: Deixa de me tocar, porque ainda não subi ao Pai; mas vai a meus irmãos e dize-lhes que eu subo para meu Pai e vosso Pai, meu Deus e vosso Deus.
+ John 20:18: E foi Maria Madalena anunciar aos discípulos que tinha visto o Senhor e que ele lhe dissera estas coisas. (PorRecebida)

- Onde mais podemos encontrar informações sobre ela?

- Tue Jan 23 11:07:28 PM -03 2024
