* Mary Magdalene: delivered from darkness[fn:1]

Now when He rose early on the first day of the week, He appeared first to Mary Magdalene, out of whom He had cast seven demons. Mark 16:9 NKJV

Mary Magdalene is one of the best-known and least understood names in Scripture. Scripture deliberately draws a curtain of silence over much of her life and personal background, but she still emerges as one of the prominent women of the New Testament. She is mentioned by name in all four gospels, mostly in connection with the events of Jesus’ crucifixion. She has the eternal distinction of being the first person to whom Christ revealed Himself after the resurrection.

Church traditions dating back to the early fathers have identified Mary Magdalene with the anonymous woman (identified only as “a sinner”) in Luke 7:37–38, who anointed Jesus’ feet and wiped them with her hair. But there is absolutely no reason to make that connection. Indeed, if we take the text of Scripture at face value, we have every reason to think otherwise. Since Luke first introduced Mary Magdalene by name in a completely different context (8:1–3) only three verses after he ended his narrative about the anointing of Jesus’ feet, it seems highly unlikely that Mary Magdalene could be the same woman whom Luke described but did not name in the preceding account. Luke was too careful a historian to neglect a vital detail like that.

Some early commentators speculated that Mary Magdalene was the woman described in John 8:1–12, caught in the very act of adultery and saved from stoning by Christ, who forgave her and redeemed her. There is no basis for that association, either.

Mary Magdalene has also been the subject of a lot of extrabiblical mythology since medieval times. During the early Middle Ages, some of the gnostic heresies virtually co-opted the character of Mary Magdalene and attached her name to a plethora of fanciful legends. Apocryphal books were written about her, including one purporting to be Mary Magdalene’s account of the life of Christ, The Gospel of Mary. Another, the gnostic Gospel of Philip, portrayed her as an adversary to Peter.

In recent years, some of those legends have been resurrected, and many of the long-discredited apocryphal stories about Mary Magdalene have been republished. She has become something of an icon for women in the “spiritual” fringe of the feminist movement who like the idea of Mary Magdalene as a kind of mythical goddess figure. Many of the ancient gnostic tales about her are well suited for that perspective. On a different front, one bestselling novel, The Da Vinci Code by Dan Brown, adapted several long-forgotten gnostic legends about Mary Magdalene and wove them into an elaborate conspiracy theory that included the blasphemous suggestion that Jesus and Mary Magdalene were secretly married and even had children. (According to that view, she, not the apostle John, was the beloved disciple mentioned in John 20:2 and 21:20.) Stacks of books ranging from utterly frivolous speculations to quasi-scholarly works have further revived selected gnostic fabrications about Mary Magdalene. A few highly sensationalized television documentaries have further reinforced the popularity of the revived myths.

So while Mary Magdalene is currently being talked about more than ever, much of the discussion is mere hype and hyperbole borrowed from ancient cults. What Scripture actually says about her is extraordinary enough without any false embellishment. Let’s not allow this truly remarkable woman to get lost in the fog of ancient heretics’ mystical and devilish fantasies.

** Darkness

Mary Magdalene did have a dark past. Nothing indicates that her conduct was ever lewd or sordid in any way that would justify the common association of her name with sins of immorality. But Mary was indeed a woman whom Christ had liberated from
demonic bondage. Luke introduced her as “Mary called Magdalene, out of whom had come seven demons” (Luke 8:2 NKJV).
Mark 16:9 also mentioned the seven demons. It’s the only detail we have been given about Mary Magdalene’s past, except for a clue that we derive from her surname.

Actually, “Magdalene” is not a surname in the modern sense. She wasn’t from a family that went by that name; she was from
the village of Magdala. She was called “Magdalene” in order to distinguish her from the other women named Mary in the New
Testament, including Mary of Bethany and Mary, the mother of Jesus.

The tiny fishing village of Magdala (mentioned only once by name in Scripture, in Matthew 15:39) was located on the northwest shore of the Sea of Galilee, some two or three miles north of the Roman city of Tiberias, and about five and a half miles south and west from Capernaum. (Capernaum, on the north shore of the lake, was Peter’s hometown and a sort of home base for Jesus’ Galilean ministry. Mary’s hometown was within easy walking distance, or accessible by a short boat trip across the corner of the lake.) Jesus’ ministry involved a number of exorcisms in that region. It seems to have been a hotbed of demonic activity.

The symptoms of demonic possession in the New Testament were varied. Demoniacs were sometimes insane, as in the case of the two demon-possessed men who lived in a graveyard and behaved so fiercely that no one dared approach them (Matt. 8:28–34; Mark 5:1–5). At least one of them, Mark tells us, was given to the nightmarish habit of deliberately mutilating himself with stones (Mark 5:5). More frequently, demonic possession was manifest in physical infirmities, such as blindness (Matt.
12:22), deafness (Mark 9:25), an inability to speak (Matt. 9:32–33), fits and seizures (Mark 1:26; Luke 9:38–40), and general infirmity (Luke 13:11–13).

Don’t imagine (as many do) that the biblical descriptions of demon possession are merely crude accommodations to human superstition, as if the maladies characterized as demonic possession in the Bible were actually manifestations of epilepsy, dementia, or other purely psychological and physiological afflictions. Scripture does make a clear distinction between demon possession and diseases, including epilepsy and paralysis (Matt. 4:24). Demon possession involves bondage to an evil spirit—a real, personal, fallen spirit-creature—that indwells the afflicted individual. In several cases, Scripture describes how evil spirits spoke through the lips of those whom they tormented (Mark 1:23–24; Luke 4:33–35). Jesus sometimes forced the demonic personality to reveal itself in that way, perhaps to give clear proof of His power over evil spirits (Mark 5:8–14).

In every case, however, demon possession is portrayed as an affliction, not a sin, per se. Lawlessness, superstition, and idolatry undoubtedly have a major role in opening a person’s heart to demonic possession, but none of the demonized individuals in the New Testament is explicitly associated with immoral behavior. They are always portrayed as tormented people, not willful malefactors. They suffered wretched indignities at the hands of evil spirits. They were all miserable, sorrowful, lonely, heartsick, forlorn, and pitiable creatures. Most of them were regarded as outcasts and pariahs by polite society. Scripture invariably presents them to us as victims with utterly ruined lives.

Such was Mary Magdalene, we can be certain. Satan tormented her with seven demons. There was nothing any mere man or woman could do for her. She was a veritable prisoner of demonic afflictions. These undoubtedly included depression, anxiety, unhappiness, loneliness, self-loathing, shame, fear, and a host of other similar miseries. In all probability, she suffered even worse torments, too, such as blindness, deafness, insanity, or any of the other disorders commonly associated with victims of demonic possession described in the New Testament. Whatever her condition, she would have been in perpetual agony—at least seven kinds of agony. Demoniacs in Scripture were always friendless, except in rare cases when devoted family members cared for them. They were perpetually restless because of their inability to escape the constant torments of their demonic captors. They were continually joyless because all of life had become darkness and misery for them. And they were hopeless because there was no earthly remedy for their spiritual afflictions.

That is all that can be said with certainty about the past of Mary Magdalene. Scripture deliberately and mercifully omits the macabre details of her dreadful demon-possession. But we are given enough information to know that at the very best, she must have been a gloomy, morose, tortured soul. And it is quite likely (especially with so many demons afflicting her) that her case was even worse. She might well have been so demented as to be regarded by most people as an unrecoverable lunatic.

** Deliverance

Christ had delivered her from all that. Luke and Mark seem to mention her former demonization only for the purpose of celebrating Christ’s goodness and grace toward her. Without dredging up any squalid details from her past, they record the fact of her bondage to demons in a way that magnifies the gracious power of Christ.

One intriguing fact stands out about all the demonic deliverances that are recorded in Scripture: demon-possessed people never came to Christ to be delivered. Usually they were brought to Him (Matt. 8:16; 9:32; 12:22; Mark 9:20). Sometimes He called them to Himself (Luke 13:12), or He went to them (Matt. 8:28–29). On occasions when demons were already present upon His arrival, they would sometimes speak out with surprise and dismay (Mark 1:23–24; Luke 8:28).

Evil spirits never voluntarily entered the presence of Christ. Nor did they ever knowingly allow one whom they possessed to come close to Him. They often cried against Him (Luke 4:34). They sometimes caused violent convulsions in a last-gasp effort to keep the wretched souls they possessed away from Him (Mark 9:20), but Christ sovereignly drew and delivered multitudes who were possessed by demons (Mark 1:34, 39). Their emancipation from demonic bondage was always instantaneous and complete.

Mary Magdalene was one of them. How and when she was delivered is never spelled out for us, but Christ set her free, and she was free indeed. Having been set free from demons and from sin, she became a slave of righteousness (Rom. 6:18). Her life was not merely reformed; it was utterly transformed.

At one point in His ministry, Jesus gave a rather poignant illustration of the inadequacy of the religion of self-reform:

When an unclean spirit goes out of a man, he goes through dry places, seeking rest; and finding none, he says, “I will return to my house from which I came.” And when he comes, he finds it swept and put in order. Then he goes and takes with him seven other spirits more wicked than himself, and they enter and dwell there; and the last state of that man is worse than the first. (Luke 11:24–26 NKJV)

It’s intriguing that Mary Magdalene herself was possessed by seven demons. Perhaps she had tried to reform her own life and learned the hard way how utterly futile it is to try to free oneself from Satan’s grip. Good works and religion don’t atone for sin (Isa. 64:6), and no sinner has it within his power to change his own heart ( Jer. 13:23). We can make cosmetic changes (sweeping the house and putting it in order), but that doesn’t remove us from the dominion of darkness into the kingdom of light. Only
God can do that (1 Peter 2:9). Only the same “God who commanded light to shine out of darkness” has the power to shine “in our hearts to give the light of the knowledge of the glory of God in the face of Jesus Christ” (2 Cor. 4:6 NKJV). That is precisely what the Lord did for Mary Magdalene.

Mary owed everything to Christ. She knew it too. Her subsequent love for Him reflected the profound depth of her gratitude.

** Discipleship

Mary Magdalene joined the close circle of disciples who traveled with Jesus on His long journeys. Her deliverance from demons may have occurred relatively late in Christ’s Galilean ministry. Luke is the only one of the gospel writers who names her in any connection prior to the crucifixion. Notice the context in which she is named:

Now it came to pass, afterward, that He went through every city and village, preaching and bringing the glad tidings of the kingdom of God. And the twelve were with Him, and certain women who had been healed of evil spirits and infirmities; Mary called Magdalene, out of whom had come seven demons, and Joanna the wife of Chuza, Herod’s steward, and Susanna, and many others who provided for Him from their substance. (Luke 8:1–3 NKJV) 

There was certainly nothing inappropriate about Jesus’ practice of allowing women disciples to be His followers. We can be certain that whatever traveling arrangements were made for the group, Jesus’ name and honor (as well as the reputations of all the men and women in the group) were carefully guarded from anything that might hint at any reproach. After all, Jesus’ enemies were looking desperately for reasons to accuse Him. If there had been any way whatsoever for them to drum up doubts about the propriety of Jesus’ relationships with women, that issue would have been raised. But even though His enemies regularly lied about Him and even accused Him of being a glutton and a winebibber (Matt. 11:19), no accusations against Him were ever made on the basis of how He treated the women in His band of disciples. These were godly women who
devoted their whole lives to spiritual things. They evidently had no family responsibilities that required them to stay home. If they had been in breach of any such duties, you can be certain that Jesus would not have permitted them to accompany Him.
There is never the slightest hint of unseemliness or indiscretion in the way any of them related to Him.

It is true that most rabbis in that culture did not normally allow women to be their disciples. But Christ encouraged men and women alike to take His yoke and learn from Him. This is yet another evidence of how women are honored in Scripture.

Luke said Mary Magdalene and the other women were among many who “provided for Him from their substance” (Luke 8:3 NKJV). Perhaps Mary had inherited financial resources that she used for the support of Jesus and His disciples. The fact that she was able to travel with Jesus in the inner circle of His disciples may be a clue that she was unmarried and otherwise free from any obligation to parents or close family. She might well have been a widow. There is no evidence that she was a very young woman. The fact that her name appears at the head of the list of this band of women seems to indicate that she had a special place of respect among them.

Mary Magdalene remained Jesus’ faithful disciple even when others forsook Him. In fact, she first appeared in Luke’s gospel at a time when opposition to Jesus had grown to the point that He began to teach in parables (Matt. 11:10–11). When others became offended with His sayings, she stayed by His side. When others walked no longer with Him, she remained faithful. She followed Him all the way from Galilee to Jerusalem for that final Passover celebration. She ended up loyally following Him to the cross, and even beyond.

** Disaster

Matthew, Mark, and John all record that Mary Magdalene was present at the crucifixion. Combining all three accounts, it is clear that she stood with Mary, the mother of Jesus, Salome (mother of the apostles James and John), and another, lesser-known Mary (mother of James the Less and Joses).

There’s an interesting progression in the gospel accounts. John, describing the state of affairs near the beginning of the crucifixion, said the women “stood by the cross” ( John 19:25 NKJV). They were close enough to hear Him speak to John and Mary when He committed His mother to the beloved disciple’s care (vv. 26–27).

But Matthew and Mark, describing the end of the ordeal, said the women were “looking on from afar” (Matt. 27:55; Mark 15:40 NKJV). As the crucifixion wore on, crowds of taunting miscreants moved in, elbowing the women back. The women probably drew back instinctively, too, as the scene became steadily more and more gruesome. It was as if they could not bear to watch—but they could not bear to leave.

They remained until the bitter end. There was nothing for them to do but watch and pray and grieve. It must have seemed the greatest possible disaster, to have the One whom they loved and trusted above all torn from their midst so violently. There they stood, in a crowd of bloodthirsty fanatics who were screaming for the death of their beloved Lord. With the screaming-mad furor of hatred at the very pinnacle of intensity, they could easily have become victims of the mob. But they never shrank away completely. They never left the scene until the bitter end. And even then, they stayed close to Jesus’ body. Such was the magnetism of their loyalty and love for Christ.

In fact, it was only thanks to Mary Magdalene that the disciples even learned where Jesus’ body was laid after His death. Mark records that Joseph of Arimathea asked Pilate for the body of Christ in order to give it a proper burial. Joseph had access to Pilate because he was a prominent member of the Sanhedrin, the ruling council of Jewish leaders (Mark 15:43). They were the same group who had conspired to bring Jesus to trial, condemned Him, and voted to put Him to death that very morning. Joseph, however, was a secret disciple of Jesus ( John 19:38), and “he had not consented to their decision and deed” (Luke 23:51 NKJV). All four gospels record Joseph’s action of retrieving Jesus’ body. Mark added that Mary Magdalene and Mary the mother of Joses secretly followed Joseph to the tomb and “observed where He was laid” (Mark 15:47 NKJV).

The apostle John described how Joseph of Arimathea, together with Nicodemus (who was “a ruler of the Jews,” according to John 3:1 NKJV, and therefore probably also a member of the Sanhedrin and a secret disciple), “took the body of Jesus, and bound it in strips of linen with the spices, as the custom of the Jews is to bury” ( John 19:40 NKJV). John says Nicodemus had purchased about a hundred pounds of “myrrh and aloes” (v. 39 NKJV). These were scented spices and resins used by the Jews in lieu of embalming. The two men speedily anointed Jesus’ body and bound Him tightly in linen strips (v. 40). They would have needed to hurry to finish the task before the Sabbath started (v. 42).

Mary Magdalene’s love for Christ was as strong as anyone’s. She took note of where and how He had been laid in the tomb. After all He had done for her, it must have broken her heart to see His lifeless, mangled body so poorly prepared and laid in a cold tomb. She was determined to wash and anoint His body properly. So Luke 23:55–56 says she and the other Mary began the preparation of their own burial spices before the Sabbath began. Mark 16:1 adds that they purchased still more spices as soon as the Sabbath was officially over (sundown on Saturday). First thing in the morning, they planned to give Him a burial worthy of Someone so profoundly loved.

** Daybreak

Mary Magdalene had remained longer than any other disciple at the cross. Then she was also the first to reach His tomb at daybreak on the first day of the week. Her devotion was never more plain than in her response to His death, and that devotion was about to be rewarded in an unimaginably triumphant way.

There was evidently no thought of resurrection in Mary Magdalene’s mind. She had seen up close the devastating effects of the bitter blows Jesus had received on the way to the cross. She had witnessed firsthand as His life ebbed from Him. She had watched as His lifeless body was unceremoniously wrapped in linen and hastily prepared ointment and left alone in the tomb.
The one thought that filled her heart was a desire to do properly what she had seen done so hurriedly and haphazardly by Nicodemus and Joseph. (She might have recognized them as members of the hostile Sanhedrin. Otherwise, she probably did not know them at all.) She thought she was coming to the tomb for one final expression of love to her Master—to whom she knew she owed everything.

The apostle John, himself an eyewitness to some of the the dramatic events of that morning, gives the best description:

Now on the first day of the week Mary Magdalene went to the tomb early, while it was still dark, and saw that the stone had been taken away from the tomb. Then she ran and came to Simon Peter, and to the other disciple, whom Jesus loved, and said to them, “They have taken away the Lord out of the tomb, and we do not know where they have laid Him.”

Peter therefore went out, and the other disciple, and were going to the tomb. So they both ran together, and the other disciple outran Peter and came to the tomb first. And he, stooping down and looking in, saw the linen cloths lying there; yet he did not go in. Then Simon Peter came, following him, and went into the tomb; and he saw the linen cloths lying there, and the handker-chief that had been around His head, not lying with the linen cloths, but folded together in a place by itself. Then the other disciple, who came to the tomb first, went in also; and he saw and believed. For as yet they did not know the Scripture, that He must rise again from the dead. Then the disciples went away again to their own homes.

But Mary stood outside by the tomb weeping, and as she wept she stooped down and looked into the tomb. And she saw two angels in white sitting, one at the head and the other at the feet, where the body of Jesus had lain. Then they said to her, “Woman, why are you weeping?”

She said to them, “Because they have taken away my Lord, and I do not know where they have laid Him.” ( John 20:1–13 NKJV)

Matthew 28:2 records that the rolling away of the stone was accompanied by “a great earthquake” (NKJV). We also know from Matthew and Mark that at least two other women (“the other Mary” and Salome) had come to help. They had discussed the difficulty of rolling the great stone (a massive wheel-shaped slab that rested in a trough) away from the mouth of the tomb, but by the time they arrived, the stone was already rolled away.

Mark 16:5 and Luke 24:3 both say the women went inside the sepulchre and found it empty. Mary’s first inclination was to assume that someone had stolen Jesus’ body. She immediately ran out of the tomb and back up the same trail she had come from, apparently planning to go for help. Before running far, though, she encountered Peter and John, on their way to the burial site. She breathlessly told them about the empty tomb, and they both took off running to see for themselves. John makes a point of recording that he outran Peter, but he stopped at the mouth of the tomb to peer inside, and Peter ran past him into the sepulchre itself. There Peter found the empty grave clothes and a headpiece folded and set aside. John joined him inside the tomb. Seeing the grave clothes still intact but empty was enough, John says, for him to believe. He and Peter left the scene immediately (Luke 24:12). It was probably at that point that the other women went into the tomb again to see for themselves (Mark 16:4).

Meanwhile, Mary Magdalene, overwrought with the new grief of thinking someone had stolen the body, remained outside the tomb alone. She stooped to peer in, and it was then that two angels appeared inside the tomb ( John 20:12). Matthew, Mark, and Luke tell the story in abbreviated fashion, deliberately truncating some details. Each account gives different aspects of the story, but they are easy to harmonize. Of course, all the women saw the angels. Only one of the angels spoke. To the women inside the tomb, he said, “He is not here; for He is risen” (Matt. 28:6; see Mark 16:6; Luke 24:6 NKJV). Then the angel instructed them, “Go quickly and tell His disciples that He is risen from the dead” (Matt. 28:7 NKJV). At that point, all but Mary seem to have left. According to Matthew, “they went out quickly from the tomb with fear and great joy” (v. 8 NKJV).

Mary seemed to have remained outside the tomb, still disconsolate over the missing body. Evidently she had taken no notice of the empty grave clothes. It seems clear that she had neither heard the angel’s triumphant news, nor did she understand how elated Peter and John were when they left the tomb. The angel came and spoke directly to her: “Woman, why are you weeping?” ( John 20:13 NKJV).

Through her broken-hearted sobs, Mary replied, “Because they have taken away my Lord, and I do not know where they have laid Him” (John 20:13 NKJV).

It was just then that she turned and saw Jesus. At first, through her tear-filled eyes, she did not recognize Him at all. (She was not the only one who did not instantly perceive who He was after His resurrection. Later that day, according to Luke 24:13–35, two of His disciples traveled some distance with Him on the road to Emmaus before their eyes were opened to realize who He was.) His countenance was different—glorified. If He looked the way John described Him in Revelation 1:14, “His head and hair were white like wool, as white as snow, and His eyes like a flame of fire” (NKJV).

Jesus spoke: “Woman, why are you weeping? Whom are you seeking?” ( John 20:15 NKJV).

Mary, thinking He was the gardener, pleaded with Him to show her where they had taken the body of Christ.

All He had to say was her name, and she instantly recognized Him. “He calls his own sheep by name . . . [and] they know his voice” ( John 10:3–4 NKJV).

“Rabboni!” Mary’s grief instantly turned to inexpressible joy ( John 20:16 NKJV), and she must have tried to clasp Him as if she would never let Him go.

His words, “Do not cling to Me” (v. 17), testified in a unique way to the extraordinary character of Mary Magdalene. Most of us are too much like the apostle Thomas—hesitant, pessimistic. Jesus urged Thomas to touch Him, in order to verify Jesus’ identity (v. 27). It is remarkable and sad—but true—that most of Jesus’ disciples, especially in this postmodern age, constantly need to be coaxed nearer to Him. Mary, by contrast, did not want to let go.

Jesus thus conferred on her a unique and unparalleled honor allowing her to be the first to see and hear Him after His resurrection. Others had already heard and believed the glad news from the mouth of an angel. Mary got to hear it first from Jesus Himself. The biblical epitaph on her life was recorded in Mark 16:9: “When He rose early on the first day of the week, He appeared first to Mary Magdalene” (NKJV).

That was her extraordinary legacy. No one can ever share that honor or take it from her. But we can, and should, seek to imitate her deep love for Christ.

* Footnotes

[fn:1] 

From the book:
Twelve Extraordinary Women
by John F. MacArthur

